type Recipe @loadModel(id: "RECIPE_MODEL") {
    id: ID!
}

# Represents an entry into a book of recipes.
# NOTE: There is no explicit book model as there is no need for one.
# The set of BookEntry models owned by an account is the entire book.
type BookEntry
  @createModel(accountRelation: LIST, description: "A recipe entry in a book") 
  @createIndex(fields: [{ path: "tag" }]) {
  recipeId: StreamID! @documentReference(model: "Recipe")
  recipe: Recipe! @relationDocument(property: "recipeId")
  title: String! @string(maxLength: 200),
  tag: String! @string(minLength: 1, maxLength: 100)
}
