type Recipe
  @createModel(accountRelation: LIST, description: "A recipe")
  @createIndex(fields: [{ path: "deleted" }]) {
  source: String! @string(maxLength: 100000)
  deleted: Boolean!
  author: DID! @documentAccount
}
